import { Lead, DashboardStats, TeamMember, Sequence, PipelineColumn, Tenant, User } from "@/types";

export const mockUser: User = {
  id: "usr_1",
  email: "demo@example.com",
  name: "Alex Morgan",
  avatar: "https://ui-avatars.com/api/?name=Alex+Morgan&background=3b82f6&color=fff",
  role: "owner",
  tenantId: "tnt_1",
};

export const mockTenant: Tenant = {
  id: "tnt_1",
  name: "Acme Corp",
  domain: "app.acme.com",
  logo: "https://ui-avatars.com/api/?name=Acme&background=0D8ABC&color=fff",
  primaryColor: "#3b82f6",
  plan: "enterprise",
  billingModel: "usage",
  targetIndustries: ["SaaS", "Fintech", "Healthcare"],
  targetCompanySize: "50-500",
  createdAt: "2024-01-15T00:00:00Z",
};

export const mockStats: DashboardStats = {
  totalLeads: 2847,
  qualifiedLeads: 634,
  conversionRate: 22.3,
  totalRevenue: 2847500,
  avgDealSize: 4500,
  aiAccuracy: 94.7,
  leadsThisMonth: 312,
  revenueThisMonth: 485000,
};

export const mockLeads: Lead[] = [
  {
    id: "lead_1",
    tenantId: "tnt_1",
    firstName: "Sarah",
    lastName: "Chen",
    email: "sarah.chen@techflow.io",
    phone: "+1 (555) 234-5678",
    company: "TechFlow Inc",
    title: "VP of Engineering",
    industry: "SaaS",
    companySize: "200-500",
    budget: "$50k-$100k",
    source: "LinkedIn",
    status: "qualified",
    score: 94,
    estimatedValue: 75000,
    assignedTo: "usr_2",
    tags: ["enterprise", "hot", "decision-maker"],
    lastActivityAt: "2024-08-29T10:30:00Z",
    createdAt: "2024-08-25T14:20:00Z",
    aiInsights: {
      score: 94,
      conversionProbability: 0.87,
      estimatedValue: 75000,
      reasons: [
        "VP-level decision maker with budget authority",
        "Company recently raised Series B ($12M)",
        "Visited pricing page 4 times in last week",
        "Downloaded enterprise security whitepaper",
        "Engaged with 3 email sequences",
      ],
      recommendedAction: "Schedule demo within 24 hours. Offer custom integration roadmap.",
      riskFactors: ["Evaluating 2 competitors", "Budget approval needed from CFO"],
      similarDeals: [
        { dealValue: 82000, closeTime: "45 days", pattern: "VP Engineering, SaaS, Series B+", similarity: 0.92 },
        { dealValue: 68000, closeTime: "38 days", pattern: "Similar engagement pattern", similarity: 0.85 },
      ],
      personalityProfile: "Data-driven, values ROI metrics and security compliance. Responds best to technical deep-dives.",
      bestContactTime: "Tuesday-Thursday, 9:00-11:00 AM PST",
      sentiment: "positive",
    },
    activities: [
      { id: "act_1", type: "page_view", description: "Viewed Enterprise Pricing page", createdAt: "2024-08-29T10:30:00Z" },
      { id: "act_2", type: "email_clicked", description: "Clicked 'See Demo' in onboarding email", createdAt: "2024-08-28T16:45:00Z" },
      { id: "act_3", type: "form_submitted", description: "Submitted 'Talk to Sales' form", createdAt: "2024-08-25T14:20:00Z" },
    ],
  },
  {
    id: "lead_2",
    tenantId: "tnt_1",
    firstName: "Marcus",
    lastName: "Johnson",
    email: "marcus@greenfield.agency",
    phone: "+1 (555) 876-1234",
    company: "Greenfield Agency",
    title: "CEO",
    industry: "Marketing",
    companySize: "10-50",
    budget: "$10k-$25k",
    source: "Referral",
    status: "proposal",
    score: 88,
    estimatedValue: 18000,
    assignedTo: "usr_3",
    tags: ["referral", "fast-track"],
    lastActivityAt: "2024-08-28T09:15:00Z",
    createdAt: "2024-08-20T11:00:00Z",
    aiInsights: {
      score: 88,
      conversionProbability: 0.72,
      estimatedValue: 18000,
      reasons: [
        "CEO with direct purchasing power",
        "Referred by existing customer (high trust)",
        "Requested proposal within 48 hours of contact",
        "Strong engagement with case studies",
      ],
      recommendedAction: "Send proposal with agency-specific templates. Include ROI calculator.",
      riskFactors: ["Limited budget range", "Needs approval from business partner"],
      similarDeals: [
        { dealValue: 22000, closeTime: "21 days", pattern: "CEO referral, small agency", similarity: 0.89 },
      ],
      personalityProfile: "Relationship-oriented, values trust and social proof. Prefers phone calls over email.",
      bestContactTime: "Monday/Wednesday, 2:00-4:00 PM EST",
      sentiment: "positive",
    },
    activities: [
      { id: "act_4", type: "meeting_booked", description: "Discovery call completed (45 min)", createdAt: "2024-08-28T09:15:00Z" },
      { id: "act_5", type: "email_opened", description: "Opened proposal request email", createdAt: "2024-08-27T08:30:00Z" },
    ],
  },
  {
    id: "lead_3",
    tenantId: "tnt_1",
    firstName: "Elena",
    lastName: "Rodriguez",
    email: "elena.rodriguez@medsync.health",
    phone: "+1 (555) 345-6789",
    company: "MedSync Health",
    title: "CTO",
    industry: "Healthcare",
    companySize: "500-1000",
    budget: "$100k+",
    source: "Conference",
    status: "negotiation",
    score: 91,
    estimatedValue: 125000,
    assignedTo: "usr_2",
    tags: ["enterprise", "healthcare", "hipaa"],
    lastActivityAt: "2024-08-29T08:00:00Z",
    createdAt: "2024-08-10T09:30:00Z",
    aiInsights: {
      score: 91,
      conversionProbability: 0.79,
      estimatedValue: 125000,
      reasons: [
        "CTO at fast-growing healthtech company",
        "Explicitly mentioned HIPAA compliance needs",
        "Attended 2 webinars on security",
        "High engagement with technical documentation",
      ],
      recommendedAction: "Schedule security review call. Prepare HIPAA BAA and SOC 2 docs.",
      riskFactors: ["Long procurement cycle (90+ days)", "Requires legal review"],
      similarDeals: [
        { dealValue: 145000, closeTime: "67 days", pattern: "Healthtech CTO, compliance focus", similarity: 0.91 },
        { dealValue: 98000, closeTime: "82 days", pattern: "Enterprise healthcare", similarity: 0.78 },
      ],
      personalityProfile: "Risk-averse, compliance-focused. Needs detailed security documentation before committing.",
      bestContactTime: "Tuesday/Thursday, 10:00 AM - 12:00 PM EST",
      sentiment: "positive",
    },
    activities: [
      { id: "act_6", type: "call_made", description: "Technical requirements call (60 min)", createdAt: "2024-08-29T08:00:00Z" },
      { id: "act_7", type: "email_clicked", description: "Downloaded security whitepaper", createdAt: "2024-08-26T14:20:00Z" },
    ],
  },
  {
    id: "lead_4",
    tenantId: "tnt_1",
    firstName: "David",
    lastName: "Kim",
    email: "david.kim@startup.xyz",
    company: "StartupXYZ",
    title: "Founder",
    industry: "SaaS",
    companySize: "1-10",
    budget: "$5k-$10k",
    source: "Organic",
    status: "new",
    score: 52,
    estimatedValue: 6000,
    tags: ["startup", "price-sensitive"],
    lastActivityAt: "2024-08-29T12:00:00Z",
    createdAt: "2024-08-29T12:00:00Z",
    aiInsights: {
      score: 52,
      conversionProbability: 0.31,
      estimatedValue: 6000,
      reasons: [
        "Early-stage founder with limited budget",
        "Signed up for free trial but no engagement",
        "Price page visited once briefly",
      ],
      recommendedAction: "Nurture with startup-focused content. Offer startup discount after 14 days.",
      riskFactors: ["Very limited budget", "High churn risk if converted", "No team buy-in signals"],
      similarDeals: [
        { dealValue: 4500, closeTime: "120 days", pattern: "Solo founder, low engagement", similarity: 0.65 },
      ],
      personalityProfile: "Cost-conscious, exploring options. Needs education on value before price discussion.",
      bestContactTime: "Weekends or evenings",
      sentiment: "neutral",
    },
    activities: [
      { id: "act_8", type: "form_submitted", description: "Signed up for free trial", createdAt: "2024-08-29T12:00:00Z" },
    ],
  },
  {
    id: "lead_5",
    tenantId: "tnt_1",
    firstName: "Jennifer",
    lastName: "Walsh",
    email: "j.walsh@retailgiant.com",
    phone: "+1 (555) 789-0123",
    company: "RetailGiant Corp",
    title: "Director of Digital",
    industry: "Retail",
    companySize: "1000+",
    budget: "$200k+",
    source: "Outbound",
    status: "contacted",
    score: 76,
    estimatedValue: 220000,
    assignedTo: "usr_4",
    tags: ["enterprise", "retail", "outbound"],
    lastActivityAt: "2024-08-27T15:30:00Z",
    createdAt: "2024-08-22T10:00:00Z",
    aiInsights: {
      score: 76,
      conversionProbability: 0.58,
      estimatedValue: 220000,
      reasons: [
        "Director-level at Fortune 500 retailer",
        "Responded to cold outreach (positive signal)",
        "Large budget potential",
      ],
      recommendedAction: "Send personalized retail case study. Request discovery call.",
      riskFactors: ["Long sales cycle typical for enterprise retail", "Multiple stakeholders involved"],
      similarDeals: [
        { dealValue: 195000, closeTime: "95 days", pattern: "Enterprise retail, outbound", similarity: 0.81 },
      ],
      personalityProfile: "Process-oriented, prefers structured evaluation. Values vendor stability and references.",
      bestContactTime: "Wednesday, 11:00 AM - 1:00 PM EST",
      sentiment: "neutral",
    },
    activities: [
      { id: "act_9", type: "email_opened", description: "Opened cold outreach email", createdAt: "2024-08-27T15:30:00Z" },
      { id: "act_10", type: "email_clicked", description: "Clicked company overview link", createdAt: "2024-08-27T15:32:00Z" },
    ],
  },
  {
    id: "lead_6",
    tenantId: "tnt_1",
    firstName: "Robert",
    lastName: "Taylor",
    email: "robert.t@financehub.com",
    company: "FinanceHub",
    title: "CIO",
    industry: "Fintech",
    companySize: "500-1000",
    budget: "$150k-$250k",
    source: "G2",
    status: "closed_won",
    score: 96,
    estimatedValue: 185000,
    assignedTo: "usr_2",
    tags: ["enterprise", "fintech", "closed"],
    lastActivityAt: "2024-08-20T16:00:00Z",
    createdAt: "2024-07-15T09:00:00Z",
    aiInsights: {
      score: 96,
      conversionProbability: 0.95,
      estimatedValue: 185000,
      reasons: [
        "CIO with direct budget control",
        "Came from high-intent G2 comparison page",
        "Completed full product trial",
        "All security requirements met",
      ],
      recommendedAction: "Closed - initiate onboarding sequence. Assign customer success manager.",
      riskFactors: [],
      similarDeals: [
        { dealValue: 210000, closeTime: "34 days", pattern: "CIO, G2 referral, full trial", similarity: 0.94 },
      ],
      personalityProfile: "Decisive, values speed and efficiency. Appreciates direct communication.",
      bestContactTime: "N/A - Customer",
      sentiment: "positive",
    },
    activities: [
      { id: "act_11", type: "score_changed", description: "AI score increased to 96", createdAt: "2024-08-18T10:00:00Z" },
      { id: "act_12", type: "meeting_booked", description: "Final negotiation call", createdAt: "2024-08-15T14:00:00Z" },
    ],
  },
];

export const mockTeam: TeamMember[] = [
  { id: "usr_2", name: "Jordan Smith", email: "jordan@example.com", avatar: "https://ui-avatars.com/api/?name=Jordan+Smith&background=10b981&color=fff", role: "Sales Manager", leadsAssigned: 145, dealsClosed: 23, revenueGenerated: 1085000, conversionRate: 15.9, status: "active" },
  { id: "usr_3", name: "Casey Lee", email: "casey@example.com", avatar: "https://ui-avatars.com/api/?name=Casey+Lee&background=f59e0b&color=fff", role: "Account Executive", leadsAssigned: 98, dealsClosed: 18, revenueGenerated: 720000, conversionRate: 18.4, status: "active" },
  { id: "usr_4", name: "Morgan Blake", email: "morgan@example.com", avatar: "https://ui-avatars.com/api/?name=Morgan+Blake&background=8b5cf6&color=fff", role: "SDR", leadsAssigned: 210, dealsClosed: 8, revenueGenerated: 145000, conversionRate: 3.8, status: "away" },
  { id: "usr_5", name: "Riley Park", email: "riley@example.com", avatar: "https://ui-avatars.com/api/?name=Riley+Park&background=ec4899&color=fff", role: "Account Executive", leadsAssigned: 112, dealsClosed: 19, revenueGenerated: 890000, conversionRate: 17.0, status: "active" },
];

export const mockSequences: Sequence[] = [
  {
    id: "seq_1",
    name: "Enterprise Nurture",
    description: "Multi-touch sequence for enterprise prospects",
    steps: [
      { id: "step_1", type: "email", subject: "Welcome to [Company]", delayDays: 0, order: 1 },
      { id: "step_2", type: "wait", delayDays: 2, order: 2 },
      { id: "step_3", type: "email", subject: "Case Study: How [Similar] grew 3x", delayDays: 3, order: 3 },
      { id: "step_4", type: "call", delayDays: 5, order: 4 },
      { id: "step_5", type: "email", subject: "Custom ROI Analysis", delayDays: 7, order: 5 },
    ],
    enrolledCount: 342,
    conversionRate: 12.4,
    isActive: true,
  },
  {
    id: "seq_2",
    name: "SMB Fast Track",
    description: "Accelerated sequence for small business leads",
    steps: [
      { id: "step_6", type: "email", subject: "Your 14-day trial starts now", delayDays: 0, order: 1 },
      { id: "step_7", type: "wait", delayDays: 1, order: 2 },
      { id: "step_8", type: "email", subject: "Quick setup guide", delayDays: 2, order: 3 },
      { id: "step_9", type: "call", delayDays: 3, order: 4 },
    ],
    enrolledCount: 567,
    conversionRate: 8.7,
    isActive: true,
  },
];

export const mockPipelineColumns: PipelineColumn[] = [
  { id: "col_new", title: "New Leads", status: "new", leads: mockLeads.filter((l) => l.status === "new"), totalValue: mockLeads.filter((l) => l.status === "new").reduce((sum, l) => sum + l.estimatedValue, 0), color: "#6b7280" },
  { id: "col_contacted", title: "Contacted", status: "contacted", leads: mockLeads.filter((l) => l.status === "contacted"), totalValue: mockLeads.filter((l) => l.status === "contacted").reduce((sum, l) => sum + l.estimatedValue, 0), color: "#3b82f6" },
  { id: "col_qualified", title: "Qualified", status: "qualified", leads: mockLeads.filter((l) => l.status === "qualified"), totalValue: mockLeads.filter((l) => l.status === "qualified").reduce((sum, l) => sum + l.estimatedValue, 0), color: "#8b5cf6" },
  { id: "col_proposal", title: "Proposal", status: "proposal", leads: mockLeads.filter((l) => l.status === "proposal"), totalValue: mockLeads.filter((l) => l.status === "proposal").reduce((sum, l) => sum + l.estimatedValue, 0), color: "#f59e0b" },
  { id: "col_negotiation", title: "Negotiation", status: "negotiation", leads: mockLeads.filter((l) => l.status === "negotiation"), totalValue: mockLeads.filter((l) => l.status === "negotiation").reduce((sum, l) => sum + l.estimatedValue, 0), color: "#f97316" },
  { id: "col_closed_won", title: "Closed Won", status: "closed_won", leads: mockLeads.filter((l) => l.status === "closed_won"), totalValue: mockLeads.filter((l) => l.status === "closed_won").reduce((sum, l) => sum + l.estimatedValue, 0), color: "#10b981" },
  { id: "col_nurture", title: "Nurture", status: "nurture", leads: [], totalValue: 0, color: "#6b7280" },
];

export const revenueData = [
  { month: "Jan", revenue: 185000, leads: 180, converted: 34 },
  { month: "Feb", revenue: 220000, leads: 210, converted: 41 },
  { month: "Mar", revenue: 195000, leads: 195, converted: 38 },
  { month: "Apr", revenue: 280000, leads: 245, converted: 52 },
  { month: "May", revenue: 310000, leads: 270, converted: 58 },
  { month: "Jun", revenue: 345000, leads: 290, converted: 65 },
  { month: "Jul", revenue: 420000, leads: 340, converted: 78 },
  { month: "Aug", revenue: 485000, leads: 312, converted: 82 },
];

export const conversionFunnelData = [
  { stage: "Website Visitors", count: 15000, percentage: 100 },
  { stage: "Leads Captured", count: 2847, percentage: 19 },
  { stage: "Contacted", count: 1890, percentage: 12.6 },
  { stage: "Qualified", count: 634, percentage: 4.2 },
  { stage: "Proposals Sent", count: 312, percentage: 2.1 },
  { stage: "Closed Won", count: 89, percentage: 0.6 },
];

export const aiPerformanceData = [
  { date: "Week 1", accuracy: 89, leadsScored: 420 },
  { date: "Week 2", accuracy: 91, leadsScored: 510 },
  { date: "Week 3", accuracy: 92, leadsScored: 480 },
  { date: "Week 4", accuracy: 93, leadsScored: 550 },
  { date: "Week 5", accuracy: 94, leadsScored: 600 },
  { date: "Week 6", accuracy: 94.7, leadsScored: 580 },
];
